FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["backendapi/backendapi.csproj", "backendapi/"]
RUN dotnet restore "backendapi/backendapi.csproj"
COPY . .
WORKDIR "/src/backendapi"
RUN dotnet build "backendapi.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "backendapi.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "backendapi.dll"]